export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_AND_PHOTOS_LOADED = 'GET_PRODUCTS_AND_PHOTOS_LOADED';
export const GET_TOTAL_PRODUCTS = 'GET_TOTAL_PRODUCTS';
export const GET_ITEM_DETAIL = 'GET_ITEM_DETAIL';
export const GET_PRODUCTS_DAILY = 'GET_PRODUCTS_DAILY';
export const GET_PRODUCTS_DAILY_AND_PHOTOS_LOADED = 'GET_PRODUCTS_DAILY_AND_PHOTOS_LOADED';
export const GET_PRODUCT_INDEX_ID = 'GET_PRODUCT_INDEX_ID';