export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT_AND_PHOTOS_LOADED = 'SET_PRODUCT_AND_PHOTOS_LOADED';
export const SET_TOTAL_PRODUCTS = 'SET_TOTAL_PRODUCTS';
export const SET_ITEM_DETAIL = 'SET_ITEM_DETAIL';
export const SET_PRODUCTS_DAILY = 'SET_PRODUCTS_DAILY';
export const SET_PRODUCT_DAILY_AND_PHOTOS_LOADED = 'SET_PRODUCT_DAILY_AND_PHOTOS_LOADED';