export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT_PHOTO_BY_NAME = 'FETCH_PRODUCT_PHOTO_BY_NAME';
export const SET_PRODUCT_PHOTOS_NOT_LOADED = 'SET_PRODUCT_PHOTOS_NOT_LOADED';
export const FETCH_PRODUCT_DETAIL = 'FETCH_PRODUCT_DETAIL';
export const FETCH_SERVICE_DETAIL = 'FETCH_SERVICE_DETAIL';
export const FETCH_PRODUCT_PHOTOS = 'FETCH_PRODUCT_PHOTOS';
export const FETCH_SERVICE_PHOTOS = 'FETCH_SERVICE_PHOTOS';
export const FETCH_PRODUCT_ITEM_PHOTOS = 'FETCH_PRODUCT_ITEM_PHOTOS';
export const FETCH_SERVICE_ITEM_PHOTOS = 'FETCH_SERVICE_ITEM_PHOTOS';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const FETCH_PRODUCTS_DAILY_DETAIL = 'FETCH_PRODUCTS_DAILY_DETAIL';
export const FETCH_PRODUCTS_DAILY = 'FETCH_PRODUCTS_DAILY';
export const FETCH_PRODUCTS_DAILY_DETAIL_PHOTOS = 'FETCH_PRODUCTS_DAILY_DETAIL_PHOTOS';
export const SET_PRODUCTS_DAILY_PHOTOS_NOT_LOADED = 'SET_PRODUCTS_DAILY_PHOTOS_NOT_LOADED';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';

export const SAVE_PRODUCT_PHOTOS = 'SAVE_PRODUCT_PHOTOS';
export const SAVE_PRODUCT_DIMENSION = 'SAVE_PRODUCT_DIMENSION';
export const SAVE_INVENTORY_QUANTITY = 'SAVE_INVENTORY_QUANTITY';
export const UPDATE_INVENTORY_QUANTITY = 'UPDATE_INVENTORY_QUANTITY';