export default {
    mutations: {
        SET_CATEGORIES: 'SET_CATEGORIES',
        SET_CATEGORIES_AND_PHOTOS_LOADED: 'SET_CATEGORIES_AND_PHOTOS_LOADED',
        SET_TOTAL_CATEGORIES: 'SET_TOTAL_CATEGORIES',
        SET_CATEGORIES_AND_PHOTOS_LOADED_TOTAL: 'SET_CATEGORIES_AND_PHOTOS_LOADED_TOTAL',
    },
    getters: {
        GET_CATEGORIES: 'GET_CATEGORIES',
        GET_TOTAL_CATEGORIES: 'GET_TOTAL_CATEGORIES',
        GET_CATEGORIES_AND_PHOTOS_LOADED: 'GET_CATEGORIES_AND_PHOTOS_LOADED',
    },
    actions: {
        SET_CATEGORY_PHOTOS_NOT_LOADED: 'SET_CATEGORY_PHOTOS_NOT_LOADED',
        FETCH_CATEGORIES: 'FETCH_CATEGORIES',
        FETCH_CATEGORY_PHOTO_BY_NAME: 'FETCH_CATEGORY_PHOTO_BY_NAME',
        FETCH_ALL_CATEGORIES: 'FETCH_ALL_CATEGORIES',
    },
};
